// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buhozqzinxhzwelrnlhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aG96cXppbnhoendlbHJubGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNDEwMDEsImV4cCI6MjA1MDkxNzAwMX0.DnLNmJjg2okJ1H6mC02wOyHl7KeOZp5DkPuxlxbR8xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);